main_job_titles = [
    "AWS",
    "ASP.NET",
    "Agile",
    "Cassandra",
    "Computer Programmer",
    "Database Administrator",
    "Database Architect",
    "Database Manager",
    "DevOps",
    "Docker",
    "Developer",
    "GraphQL",
    "Haskell",
    "Jira",
    "Kubernetes",
    "MongoDB",
    "MySQL",
    "Pandas",
    "PHP Developer",
    "PostgreSQL",
    "Product Manager",
    "Quality Assurance",
    "Web Designer",
    "Objective-C Developer",
    "Redis",
    "Scrum Master",
    "Vue.Js",
    "Account Coordinator",
    "Account Executive",
    "Account Manager",
    "Accountant",
    "Accounting Clerk",
    "Accounts Payable Specialist",
    "Accounts Receivable Specialist",
    "Activities Coordinator",
    "Actor",
    "Actuary",
    "Acupuncturist",
    "Additive Manufacturing Scientist",
    "Administrative Assistant",
    "Administrative Services Manager",
    "Admissions Counselor",
    "Adult Education Teacher",
    "Advanced Practice Provider",
    "Advertising Manager",
    "Advertising Sales Representative",
    "Aerospace Engineer",
    "Agricultural Engineer",
    "Agricultural Equipment Operator",
    "Agricultural Inspector",
    "Agricultural Technician",
    "Agriculture Teacher",
    "Agronomist",
    "AI Ethics Consultant",
    "AI Research Scientist",
    "Aide",
    "Air Traffic Controller",
    "Aircraft Mechanic",
    "Aircraft Service Technician",
    "Airline Pilot",
    "Ambulance Driver",
    "Amusement Machine Technician",
    "Anesthesiologist",
    "Animal Caretaker",
    "Animal Control Officer",
    "Animal Cruelty Investigator",
    "Animal Nutritionist",
    "Animal Researcher",
    "Animal Scientist",
    "Animal Shelter Manager",
    "Animator",
    "Anthropologist",
    "Appliance Repair Technician",
    "Applied Research Scientist",
    "Archaeologist",
    "Architect",
    "Architectural Drafter",
    "Architectural Manager",
    "Archivist",
    "Art Teacher",
    "Artist",
    "Assembler",
    "Assembly Line Worker",
    "Assistant Buyer",
    "Assistant Professor",
    "Astronomer",
    "Astrophysicist",
    "Athletic Trainer",
    "ATM Technician",
    "Atmospheric Scientist",
    "Attorney",
    "Audio Technician",
    "Audiologist",
    "Auditor",
    "Augmented Reality Developer",
    "Author",
    "Authorizer",
    "Auto Body Technician",
    "Auto Glass Repair Technician",
    "Auto Glass Technician",
    "Autobody Technician",
    "Automotive Service Technician",
    "Automotive Technician",
    "Autonomous Vehicle Engineer",
    "Avionics Technician",
    "B2B Sales Representative",
    "Baggage Handler",
    "Bailiff",
    "Baker",
    "Bank Teller",
    "Banking Specialist",
    "Barback",
    "Barber",
    "Barista",
    "Bartender",
    "Beautician",
    "Beekeeper",
    "Bellhop",
    "Bicycle Mechanic",
    "Big Data Analyst",
    "Billing Clerk",
    "Bindery Operator",
    "Biochemist",
    "Bioengineer",
    "Biological Engineer",
    "Biological Scientist",
    "Biological Technician",
    "Biologist",
    "Biology Teacher",
    "Biomedical Engineer",
    "Biophysicist",
    "Biotechnology Project Manager",
    "Block Mason",
    "Blockchain Architect",
    "Blockchain Specialist",
    "Boat Adventure Tour Guide",
    "Boat Mechanic",
    "Boiler Operator",
    "Boilermaker",
    "Bookkeeper",
    "Bookkeeping Clerk",
    "Brake Technician",
    "Brand Manager",
    "Bread Baker",
    "Brick Mason",
    "Bridal Consultant",
    "Bridal Stylist",
    "Bridge Operator",
    "Broadcast Technician",
    "Budget Analyst",
    "Building Inspector",
    "Bus Driver",
    "Bus Mechanic",
    "Bus Operator",
    "Business Analyst",
    "Business Development Manager",
    "Business Education Teacher",
    "Business Intelligence Analyst",
    "Business Intelligence Developer",
    "Business Manager",
    "Business Operations Manager",
    "Business Reporter",
    "Butcher",
    "Cabinetmaker",
    "Cafeteria Cook",
    "Cafeteria Worker",
    "Calibration Specialist",
    "Calibration Technician",
    "Call Center Agent",
    "Call Center Operator",
    "Call Center Representative",
    "Camera Inspection Technician",
    "Camera Operator",
    "Camera Repair Technician",
    "Captioner",
    "Cardiologist",
    "Cardiovascular Technician",
    "Cardiovascular Technologist",
    "Career Education Teacher",
    "Caregiver",
    "Cargo Agent",
    "Carpenter",
    "Carpentry Worker",
    "Carpet Installer",
    "Cartographer",
    "Case Manager",
    "Cash Office Clerk",
    "Cashier",
    "Casino Host",
    "Caster",
    "Cathode Scientist",
    "CATV Installer",
    "Ceiling Tile Installer",
    "Cement Mason",
    "Certified Nursing Assistant (CNA)",
    "Certified Pharmacy Technician",
    "Channel Account Executive",
    "Chef",
    "Chemical Engineer",
    "Chemical Equipment Operator",
    "Chemical Plant Operator",
    "Chemical Technician",
    "Chemist",
    "Chemistry Teacher",
    "Chief Data Officer",
    "Chief Executive Officer",
    "Chief Financial Officer",
    "Chief of Staff",
    "Chief Operating Officer",
    "Chief Operations Officer",
    "Chief Revenue Officer",
    "Chief Sustainability Officer",
    "Child Social Worker",
    "Childcare Administrator",
    "Childcare Worker",
    "Chiropractor",
    "Choreographer",
    "Civil Construction Worker",
    "Civil Drafter",
    "Civil Engineer",
    "Civil Engineering Technician",
    "Civil Engineering Technologist",
    "Claims Adjuster",
    "Claims Examiner",
    "Claims Investigator",
    "Cleaner",
    "Cleaning Equipment Operator",
    "Clergy",
    "Clerical Worker",
    "Clerk",
    "Client Services Coordinator",
    "Client Services Manager",
    "Clinical Laboratory Scientist",
    "Clinical Laboratory Technician",
    "Clinical Laboratory Technologist",
    "Clinical Pharmacist",
    "Clinical Psychologist",
    "Clinical Research Coordinator",
    "CNC Machine Operator",
    "CNC Operator",
    "CNC Programmer",
    "Coach",
    "Coating Operator",
    "Coil Winder",
    "Collection Agent",
    "Collections Specialist",
    "College Instructor",
    "College Professor",
    "College Teaching Assistant",
    "Commercial Designer",
    "Commercial Diver",
    "Commercial Pilot",
    "Commodities Sales Agent",
    "Communications Manager",
    "Communications Operator",
    "Communications Specialist",
    "Communications Teacher",
    "Community Association Manager",
    "Community Corrections Specialist",
    "Community Health Worker",
    "Community Service Specialist",
    "Community Specialist",
    "Compensation Advisor",
    "Compensation and Benefits Manager",
    "Compensation Specialist",
    "Compliance Engineer",
    "Compliance Officer",
    "Compliance Specialist",
    "Computational Scientist",
    "Computer and Information Systems Manager",
    "Computer Network Architect",
    "Computer Network Support Specialist",
    "Computer Science Teacher",
    "Computer Support Specialist",
    "Computer Systems Analyst",
    "Concierge",
    "Conciliator",
    "Concrete Finisher",
    "Conservation Forester",
    "Conservationist",
    "Construction Helper",
    "Construction Inspector",
    "Construction Laborer",
    "Construction Manager",
    "Consultant",
    "Consumer Science Teacher",
    "Content Designer",
    "Content Marketing Manager",
    "Content Writer",
    "Continuous Improvement Lead",
    "Continuous Mining Operator",
    "Control Room Operator",
    "Controller",
    "Conveyor Mechanic",
    "Conveyor Technician",
    "Cook",
    "Copy Editor",
    "Copywriter",
    "Corporate Counsel",
    "Correction Specialist",
    "Correctional Officer",
    "Correspondence Clerk",
    "Cosmetology Instructor",
    "Cost Estimator",
    "Costume Attendant",
    "Counselor",
    "Counter Clerk",
    "Courier",
    "Court Clerk",
    "Court Reporter",
    "CPU Research Scientist",
    "Craft Artist",
    "Crane Operator",
    "Crane Rigger",
    "Creative Director",
    "Credit Analyst",
    "Crematory Operator",
    "Criminal Investigator",
    "Criminal Justice Teacher",
    "Crossing Guard",
    "Cryptocurrency Trader",
    "Culinary Chef",
    "Cultural Studies Teacher",
    "Curator",
    "Customer Care Associate",
    "Customer Marketing Manager",
    "Customer Service Manager",
    "Customer Service Representative",
    "Customer Success Associate",
    "Cutter",
    "Cutting Machine Operator",
    "Cybersecurity Analyst",
    "Cybersecurity Strategist",
    "Cytotechnologist",
    "Dance Instructor",
    "Dancer",
    "Data Analyst",
    "Data Architect",
    "Data Entry Clerk",
    "Data Scientist",
    "Daycare Administrator",
    "Deal Deal Manager",
    "Dealer",
    "Delivery Driver",
    "Delivery Manager",
    "Demand Generation Director",
    "Demonstrator",
    "Dental Assistant",
    "Dental Hygienist",
    "Dental Laboratory Technician",
    "Dentist",
    "Deputy",
    "Dermatologist",
    "Designer",
    "Desktop Publisher",
    "Desktop Support Technician",
    "Detective",
    "Development Manager",
    "Diagnostic Radiologist",
    "Die Designer",
    "Diesel Engine Specialist",
    "Dietetic Technician",
    "Dietitian",
    "Digital Health Coach",
    "Digital Marketing Specialist",
    "Digital Transformation Lead",
    "Dining Room Manager",
    "Director of Bioinformatics",
    "Director",
    "Disc Jockey",
    "Dishwasher",
    "Dispatcher",
    "Distribution Manager",
    "Distribution Supervisor",
    "Diversity and Inclusion Manager",
    "Doctor",
    "Door to Door Sales Worker",
    "Dorm Supervisor",
    "Drafter",
    "Drama Teacher",
    "Dredge Operator",
    "Dressmaker",
    "Drill Rig Operator",
    "Driller",
    "Drilling Machine Tool Operator",
    "Driver",
    "Drone Pilot",
    "Drug Delivery",
    "Drywall Finisher",
    "Drywall Installer",
    "Drywall Technician",
    "Dye Operator",
    "E-commerce Consultant",
    "E-commerce Market Manager",
    "Early Childhood Special Education Teacher",
    "Early Childhood Teacher",
    "Earth Science Teacher",
    "Echo Technologist",
    "Economics Teacher",
    "Economist",
    "Editor",
    "Edtech Specialist",
    "Education Administrator",
    "Education Teacher",
    "Educational Technology Specialist",
    "Educator",
    "Electrical Distribution Operator",
    "Electrical Engineer",
    "Electrician Helper",
    "Electrician",
    "Electrologist",
    "Electromechanical Technician",
    "Electronics Engineer",
    "Elementary Special Education Teacher",
    "Elevator Mechanic",
    "Eligibility Interviewer",
    "Email Campaign Manager",
    "Embalmer",
    "Emergency Dispatcher",
    "Emergency Management Director",
    "Emergency Medical Technician",
    "Emergency Medicine Physician",
    "Employee Relations Specialist",
    "Engineer",
    "Engineering Manager",
    "Engineering Teacher",
    "English Teacher",
    "Engraver",
    "Entertainer",
    "Entertainment Manager",
    "Environmental Engineer",
    "Environmental Engineering Technician",
    "Environmental Scientist",
    "Epidemiologist",
    "Equipment Operator",
    "Escalator Mechanic",
    "ESL Teacher",
    "Estate Agent",
    "Esthetician",
    "Estimator",
    "Etcher",
    "Event Coordinator",
    "Event Manager",
    "Event Staff",
    "Excursion Guide",
    "Executive Administrative Assistant",
    "Executive Assistant",
    "Executive Chef",
    "Executive Recruiter",
    "Executive Secretary",
    "Exercise Physiologist",
    "Exercise Trainer",
    "Expediter",
    "Explosives Worker",
    "Fabricator",
    "Facilities Manager",
    "Facility Manager",
    "Faculty",
    "Family Medicine Physician",
    "Family Social Worker",
    "Family Teacher",
    "Farm and Home Management Educator",
    "Farm Equipment Mechanic",
    "Farm Manager",
    "Farm Technician",
    "Farm worker",
    "Farmer",
    "Fashion Designer",
    "Fashion Stylist",
    "Fast Service Worker",
    "Fence Installer",
    "Fiberglass Fabricator",
    "Fiberglass Laminator",
    "Field Mechanic",
    "Field Sales Representative",
    "File Clerk",
    "Film Editor",
    "Film Processor",
    "Film Producer",
    "Finance Manager",
    "Financial Advisor",
    "Financial Analyst",
    "Financial Auditor",
    "Financial Clerk",
    "Financial Counselor",
    "Financial Examiner",
    "Financial Manager",
    "Financial Planner",
    "Financial Risk Specialist",
    "Financial Sales Agent",
    "Financial Services Representative",
    "Financial Specialist",
    "Fine Artist",
    "Fire Inspector",
    "Fire Investigator",
    "Fire Protection Engineer",
    "Firefighter",
    "Fish and Game Warden",
    "Fitness Instructor",
    "Fitness Trainer",
    "Flagger",
    "Flight Attendant",
    "Flight Engineer",
    "Floor Layer",
    "Floral Designer",
    "Food and Beverage Manager",
    "Food Batchmaker",
    "Food Production Machine Operator",
    "Food Scientist",
    "Food Service Manager",
    "Foreign Language Teacher",
    "Forensic Science Technician",
    "Forester",
    "Forestry Teacher",
    "Forestry Technician",
    "Forging Machine Operator",
    "Forklift Operator",
    "Formulation Scientist",
    "Foundry Worker",
    "Freelance Photographer",
    "Freight Agent",
    "Front Desk Clerk",
    "Front Desk Coordinator",
    "Fundraiser",
    "Fundraising Manager",
    "Funeral Attendant",
    "Funeral Home Manager",
    "Furnace Repair Technician",
    "Furniture Finisher",
    "Furniture Upholsterer",
    "Gaming Enforcement Agent",
    "Gaming Manager",
    "Garbage Collector",
    "Gardener",
    "Garment Presser",
    "Gas Compressor Operator",
    "Gas Plant Operator",
    "General Labor",
    "General Manager",
    "General Worker",
    "Genetic Counselor",
    "Geographer",
    "Geography Teacher",
    "Geological Engineer",
    "Geological Technician",
    "Geologist",
    "Geophysicist",
    "Geoscientist",
    "Glazier",
    "Goldsmith",
    "GPS Coordinator",
    "GPS Technician",
    "Graduate Teaching Assistant",
    "Graphic Designer",
    "Green Energy Consultant",
    "Grill Operator",
    "Groomer",
    "Grounds Maintenance Worker",
    "Group Fitness Instructor",
    "Guest Room Attendant",
    "Guidance Counselor",
    "Gymnastics Coach",
    "Gynecologist",
    "Hairdresser",
    "Hand Grinder",
    "Hardware Engineer",
    "Hazardous Material",
    "Hazmat",
    "Head Cook",
    "Head of Engineering",
    "Head of Operations",
    "Health and Safety Engineer",
    "Health Education Specialist",
    "Health Information Technician",
    "Health Information Technologist",
    "Health Specialties Teacher",
    "Healthcare Analyst",
    "Healthcare Practitioner",
    "Healthcare Social Worker",
    "Hearing Aid Specialist",
    "Hearing Officer",
    "Heavy Equipment Operator",
    "Help Desk Assistant",
    "Help Desk Technician",
    "Helper",
    "High School Special Education Teacher",
    "High Ticket Closer",
    "Highway Maintenance Worker",
    "Historian",
    "History Teacher",
    "Home Health Aide",
    "Horticulturist",
    "Host or Hostess",
    "Hot Tub Repair Technician",
    "Hotel Clerk",
    "Hotel Manager",
    "Housekeeper",
    "Housekeeping Supervisor",
    "HR Consultant",
    "HR Director",
    "HR Generalist",
    "HR Manager",
    "HR Specialist",
    "HR System Administrator",
    "Human Resources Assistant",
    "HVAC Technician",
    "Hydrologic Technician",
    "Hydrologist",
    "Illustrator",
    "Industrial Designer",
    "Industrial Engineer",
    "Industrial Machinery Mechanic",
    "Industrial Production Manager",
    "Industrial Truck and Tractor Operator",
    "Industrial-Organizational Psychologist",
    "Information Security Analyst",
    "Inside Sales Representative",
    "Inspector",
    "Institutional Cook",
    "Instructional Coordinator",
    "Instructional Designer",
    "Instructor",
    "Instrument Repair Technician",
    "Insulation Worker",
    "Insurance Appraiser",
    "Insurance Claims Clerk",
    "Insurance Sales Agent",
    "Insurance Underwriter",
    "Intellectual Property Lawyer",
    "Intercity Bus Driver",
    "Interface Designer",
    "Interior Designer",
    "Internal Medicine Physician",
    "International HR Associate",
    "Interpreter",
    "Interviewer",
    "Inventory Manager",
    "Investment Analyst",
    "Investment Banking Analyst",
    "Investment Sales Agent",
    "Iron Worker",
    "Ironworker",
    "Irrigation Technician",
    "IT Consultant",
    "IT Help Desk Support",
    "IT Manager",
    "IT Support Specialist",
    "Janitor",
    "Janitorial Worker",
    "Jeweler",
    "Journalist",
    "Judge",
    "Kennel Attendant",
    "Kindergarten Teacher",
    "Lab Animal Caretaker",
    "Lab Assistant",
    "Lab Technician",
    "Labor Relations Specialist",
    "Laborer",
    "Land Surveyor",
    "Landscape Architect",
    "Landscaper",
    "Lathe and Turning Machine Tool Setter",
    "Laundry Worker",
    "Law Enforcement Teacher",
    "Lawn Technician",
    "Lawyer",
    "Layout Worker",
    "Learning and Development Specialist",
    "Legal Assistant",
    "Legal Secretary",
    "Legislative Aide",
    "Librarian",
    "Library Assistant",
    "Library Technician",
    "Licensed Physical Therapist Assistant",
    "Licensed Practical Nurse",
    "Licensed Therapist",
    "Licensed Vocational Nurse",
    "Life Scientist",
    "Lifeguard",
    "Light Truck Driver",
    "Lighting Engineer",
    "Lighting Technician",
    "Line Cook",
    "Line Installer",
    "Lineman",
    "Literature Teacher",
    "Litigation Paralegal",
    "Loan Officer",
    "Locker Room Attendant",
    "Locksmith",
    "Locomotive Engineer",
    "Lodging Manager",
    "Logging Equipment Operator",
    "Logistician",
    "Logistics Coordinator",
    "Loss Prevention Specialist",
    "LPN (Licensed Practical Nurse)",
    "Lua Developer"
    "Machine Operator",
    "Machinist",
    "Magistrate Judge",
    "Maid",
    "Mail Carrier",
    "Mail Clerk",
    "Mail Sorter",
    "Maintenance Technician",
    "Makeup Artist",
    "Mammography Technologist",
    "Management Analyst",
    "Manager",
    "Manicurist",
    "Manufactured Home Installer",
    "Mapping Technician",
    "Marine Biologist",
    "Marine Conservation Scientist",
    "Marine Engineer",
    "Marine Oiler",
    "Market Research Analyst",
    "Marketing Coordinator",
    "Marketing Director",
    "Marketing Manager",
    "Marketing Specialist",
    "Marriage and Family Therapist",
    "Mason",
    "Massage Therapist",
    "Materials Engineer",
    "Materials Scientist",
    "Math Teacher",
    "Mathematical Science Teacher",
    "Mathematical Scientist",
    "Mathematician",
    "Meat Cutter",
    "Meat Inspector",
    "Mechanic",
    "Mechanical Door Repairer",
    "Mechanical Drafter",
    "Mechanical Engineer",
    "Mechanical Technologist",
    "Media and Communication Equipment Worker",
    "Mediator",
    "Medical and Health Services Manager",
    "Medical Appliance Technician",
    "Medical Assistant",
    "Medical Billing Specialist",
    "Medical Coder",
    "Medical Doctor (MD)",
    "Medical Dosimetrist",
    "Medical Equipment Preparer",
    "Medical Equipment Repairer",
    "Medical Office Receptionist",
    "Medical Records Specialist",
    "Medical Registrar",
    "Medical Scientist",
    "Medical Secretary",
    "Medical Transcriptionist",
    "Meeting Planner",
    "Mental Health Aide",
    "Mental Health Counselor",
    "Mental Health Physician",
    "Mental Health Social Worker",
    "Mental Health Technician",
    "Merchandise Displayer",
    "Merchandiser",
    "Messenger",
    "Metal Fabricator",
    "Metal Pourer",
    "Metal Worker",
    "Meter Reader",
    "Microbiologist",
    "Microbiome Researcher",
    "Middle School Special Education Teacher",
    "Milling Machine Setter",
    "Millwright",
    "Mine Operator",
    "Mining and Geological Engineer",
    "Mining Bolter",
    "Ministry Worker",
    "Miscellaneous Assembler",
    "Mixed Reality Developer",
    "Mobile Heavy Equipment Mechanic",
    "Model Maker",
    "Molder",
    "Molecular Technologist",
    "Mortician",
    "Motion Picture Projectionist",
    "Motorboat Operator",
    "Motorcycle Mechanic",
    "MRI Technologist",
    "Multimedia Animator",
    "Multimedia Specialist",
    "Museum Technician",
    "Music Director",
    "Music Teacher",
    "Musical Instrument Repairer",
    "Musician",
    "Nail Technician",
    "NASA Research Scientist",
    "National Sales Manager",
    "Natural Sciences Manager",
    "Network Administrator",
    "Network Engineer",
    "Neurologist",
    "New Accounts Clerk",
    "News Analyst",
    "News Journalist",
    "News Reporter",
    "Non-Emergency Medical Driver",
    "Non-Retail Sales Worker",
    "Notary",
    "Nuclear Engineer",
    "Nuclear Medicine Technologist",
    "Nuclear Power Reactor Operator",
    "Nuclear Technician",
    "Nurse Aide",
    "Nurse Anesthetist",
    "Nurse Midwife",
    "Nurse Practitioner",
    "Nurse",
    "Nursing Assistant",
    "Nursing Instructor",
    "Nutritionist",
    "OB/GYN",
    "Obstetrician",
    "Occupational Safety Specialist",
    "Occupational Safety Technician",
    "Occupational Therapist",
    "Occupational Therapy Assistant",
    "Office Appliance Repairer",
    "Office Assistant",
    "Office Clerk",
    "Office Coordinator",
    "Office Manager",
    "Oil Field Worker",
    "Operating Room Assistant",
    "Operating Room Technician",
    "Operations Analyst",
    "Operations Assistant",
    "Operations Director",
    "Operations Manager",
    "Operations Research Analyst",
    "Operations Specialist",
    "Operator",
    "Ophthalmic Laboratory Technician",
    "Ophthalmic Medical Technician",
    "Ophthalmologist",
    "Optician",
    "Optometrist",
    "Oral Surgeon",
    "Order Clerk",
    "Order Filler",
    "Organizational Development Specialist",
    "Orthodontist",
    "Orthopedic Surgeon",
    "Orthotist",
    "Packaging Machine Operator",
    "Packaging Operator",
    "Packer",
    "Painter",
    "Painting Operator",
    "Paperhanger",
    "Paralegal",
    "Paramedic",
    "Parking Attendant",
    "Parking Enforcement Worker",
    "Parts Salesperson",
    "Passenger Attendant",
    "Pastry Chef",
    "Pathologist",
    "Patient Care Technician",
    "Pattern Maker",
    "Paving Equipment Operator",
    "Payroll Specialist",
    "Pediatrician",
    "Pedicurist",
    "Performer",
    "Permanent Makeup Artist",
    "Personal Assistant",
    "Personal Financial Advisor",
    "Personal Service Manager",
    "Personal Trainer",
    "Pest Control Worker",
    "Pesticide Handler",
    "Pet Sitter",
    "Pet Walker",
    "Petroleum Engineer",
    "Petroleum Operator",
    "Pharmacist",
    "Pharmacy Aide",
    "Pharmacy Assistant",
    "Pharmacy Clerk",
    "Pharmacy Technician",
    "Philosophy Professor",
    "Phlebotomist",
    "Photo Lab Technician",
    "Photographer",
    "Photovoltaic Installer",
    "Physical Science Technician",
    "Physical Scientist",
    "Physical Therapist Aide",
    "Physical Therapist Assistant",
    "Physical Therapist",
    "Physical Therapy Aide",
    "Physical Therapy Assistant",
    "Physician Assistant",
    "Physician",
    "Physicist",
    "Physics Instructor",
    "Pile Driver Operator",
    "Pipe Foreman",
    "Pipefitter",
    "Pipelayer",
    "Pipeline Installer",
    "Pizza Cook",
    "Plant Biologist",
    "Plant Nursery Attendant",
    "Plant Operator",
    "Plasterer",
    "Platforms Manager",
    "Plating Operator",
    "Plating Technician",
    "Plumber",
    "Podiatrist",
    "Police Officer",
    "Policy Analyst",
    "Polisher",
    "Political Scientist",
    "Pool Maintenance Technician",
    "Porter",
    "Portrait Photographer",
    "Postal Carrier",
    "Postal Clerk",
    "Postmaster",
    "Power Dispatcher",
    "Power Equipment Mechanic",
    "Power Plant Operator",
    "Practitioner",
    "Precision Agriculture Advisor",
    "Prep Cook",
    "Prepress Technician",
    "Preschool Administrator",
    "Preschool Teacher",
    "President",
    "Press Machine Operator",
    "Press Operator",
    "Principal",
    "Print Binding Worker",
    "Print Machine Operator",
    "Privacy Consultant",
    "Private Chef",
    "Private Cook",
    "Private Household Cook",
    "Private Investigator",
    "Private Tutor",
    "Probation Officer",
    "Procurement Clerk",
    "Procurement Manager",
    "Procurement Specialist",
    "Producer",
    "Product Engineer",
    "Product Marketing Manager",
    "Product Operations Manager",
    "Product Owner",
    "Production Clerk",
    "Production Operator",
    "Production Planner",
    "Production Supervisor",
    "Production Worker",
    "Professional Athlete",
    "Program Manager",
    "Project Coordinator",
    "Project Manager",
    "Projection Geotechnical Engineer",
    "Promotions Manager",
    "Prompt Engineer",
    "Proofreader",
    "Property Appraiser",
    "Property Manager",
    "Prosthetist",
    "Prosthodontist",
    "Protection Officer",
    "Psychiatric Aide",
    "Psychiatric Technician",
    "Psychiatrist",
    "Psychologist",
    "Psychology Professor",
    "Public Health Nurse",
    "Public Relations Manager",
    "Public Relations Specialist",
    "Public Safety Telecommunicator",
    "Public School Teacher",
    "Public Works",
    "Pump Operator",
    "Pump Technician",
    "Purchasing Agent",
    "Purchasing Clerk",
    "Purchasing Manager",
    "QA Analyst",
    "QA Auditor",
    "QA Manager",
    "Quality Assurance Manager",
    "Quality Assurance Specialist",
    "Quality Control Inspector",
    "Quantum Computing Analyst",
    "Quarry Worker",
    "Radiation Therapist",
    "Radio Disc Jockey",
    "Radio Equipment Installer",
    "Radio/TV Announcer",
    "Radiologic Technologist",
    "Radiologist",
    "Radiology Technologist",
    "Rail Car Mechanic",
    "Rail Car Repairer",
    "Rail Maintenance Operator",
    "Rail Worker",
    "Rail Yard Engineer",
    "Railroad Conductor",
    "Railroad Police Officer",
    "Real Estate Agent",
    "Real Estate Appraiser",
    "Real Estate Attorney",
    "Real Estate Broker",
    "Realtor",
    "Rebar Worker",
    "Receptionist",
    "Recreation Attendant",
    "Recreation Manager",
    "Recreation Studies Professor",
    "Recreation Worker",
    "Recreational Therapist",
    "Recruiter",
    "Recycling Collector",
    "Referee",
    "Refinery Operator",
    "Refractory Repair Technician",
    "Refrigerator Mechanic",
    "Refuse Collector",
    "Regional Planner",
    "Regional Sales Manager",
    "Registered Nurse",
    "Rehabilitation Counselor",
    "Religion Teacher",
    "Remote Learning Facilitator",
    "Rental Clerk",
    "Research and Development Technician",
    "Research Assistant",
    "Research Physicist",
    "Research Scientist",
    "Reservation Agent",
    "Resident Advisor",
    "Resort Desk Clerk",
    "Respiratory Care Practitioner",
    "Respiratory Therapist",
    "Restaurant Cook",
    "Restaurant Manager",
    "Retail Pharmacist",
    "Retail Sales Associate",
    "Retail Salesperson",
    "Retail Store Manager",
    "Revenue Agent",
    "Revenue Management",
    "Rig Operator",
    "Rigger Helper",
    "Rigger",
    "Rigging Technician",
    "Risk Manager",
    "Robotics Engineer",
    "Rock Climbing Guide",
    "Rock Splitter",
    "Rolling Machine Operator",
    "Roof Bolter",
    "Roofer",
    "Roofing Technician",
    "Roustabout",
    "RV Service Technician",
    "Safety Engineer",
    "Safety Inspector",
    "Safety Manager",
    "Safety Officer",
    "Sailor",
    "Sales Associate",
    "Sales Clerk",
    "Sales Compensation Manager",
    "Sales Consultant",
    "Sales Development Representative",
    "Sales Director",
    "Sales Engineer",
    "Sales Manager",
    "Sales Representative",
    "Salon Manager",
    "Sandblaster",
    "Saw Operator",
    "Sawmill Operator",
    "Scaffold Helper",
    "School Bus Driver",
    "School Bus Monitor",
    "School Psychologist",
    "School Social Worker",
    "Science Teacher",
    "Scientist Plasma Materials",
    "Scout",
    "Sculptor",
    "Sea Mate",
    "Sea Pilot",
    "Search Engine Analyst",
    "Search Engine Developer",
    "Search Engine Evaluator",
    "Search Engine Marketer",
    "Search Engine Optimization Specialist",
    "Secondary Education Teacher",
    "Secretary",
    "Securities Sales Specialist",
    "Security Guard",
    "Security Officer",
    "Security Screener",
    "Security Systems Installer",
    "Semiconductor Technician",
    "Senior Process Engineer",
    "SEO Specialist",
    "Septic Tank Servicer",
    "Server",
    "Service Advisor",
    "Service Desk Analyst",
    "Service Unit Operator",
    "Service Writer",
    "Set Designer",
    "Sewing Attendant",
    "Sewing Machine Operator",
    "Shampooer",
    "Sheet Metal Worker",
    "Shift Lab Technician",
    "Ship Captain",
    "Ship Engineer",
    "Shipping Clerk",
    "Short Order Cook",
    "Shuttle Driver",
    "Signal Operator",
    "Singer",
    "Skilled Laborer",
    "Skin Care Specialist",
    "Smart Grid Engineer",
    "Social Media Coordinator",
    "Social Media Manager",
    "Social Researcher",
    "Social Service Assistant",
    "Social Service Manager",
    "Social Worker",
    "Sociologist",
    "Software Quality Assurance Analyst",
    "Software Research Scientist",
    "Soil Conservation Scientist",
    "Soil Scientist",
    "Solar Helper",
    "Solar Installer",
    "Solderer",
    "Sommelier",
    "Sonographer",
    "Sound Engineer",
    "Sous Chef",
    "Spa Manager",
    "Space Science Engineer",
    "Space Science Teacher",
    "Space Scientist",
    "Space Tourism Guide",
    "Special Education Teacher",
    "Special Effects Animator",
    "Special Effects Artist",
    "Specialist Surgeon",
    "Speech-Language Pathologist",
    "Sports Agent",
    "Sports Coach",
    "Spray Machine Operator",
    "Staff Nurse",
    "Staff Pharmacist",
    "Staff Scientist",
    "Stationary Engineer",
    "Statistical Assistant",
    "Statistician",
    "Steel Worker",
    "Stitcher",
    "Stocker",
    "Stone Mason",
    "Store Clerk",
    "Store Manager",
    "Storm Shelter Installer",
    "Strategy Manager",
    "Street Vendor",
    "Streetcar Operator",
    "Stucco Mason",
    "Substance Abuse Counselor",
    "Substitute Teacher",
    "Superintendent",
    "Supervisor",
    "Supply Chain Coordinator",
    "Supply Chain Specialist",
    "Surgeon",
    "Surgical Assistant",
    "Surgical Technologist",
    "Surveillance Officer",
    "Survey Analyst",
    "Survey Researcher",
    "Survey Technician",
    "Surveyor",
    "Sustainability Advocate",
    "Sustainability Analyst",
    "Sustainable Packaging Designer",
    "Switchboard Operator",
    "Systems Administrator",
    "Tailor",
    "Talent Acquisition Coordinator",
    "Talent Acquisition Specialist",
    "Tank Loader",
    "Taper",
    "Tattoo Artist",
    "Tax Attorney",
    "Tax Consultant",
    "Tax Examiner",
    "Tax Preparer",
    "Taxi Driver",
    "Teacher",
    "Teacher’s Aide",
    "Team Lead",
    "Technical Ops Scientist",
    "Technical Writer",
    "Telecommunications Equipment Installer",
    "Telemarketer",
    "Telemedicine Coordinator",
    "Telephone Operator",
    "Television Director",
    "Teller",
    "Temporary Teacher",
    "Territory Sales Manager",
    "Test Administrator",
    "Theater Usher",
    "Theoretical Physicist",
    "Therapist",
    "Tile Setter",
    "Title Examiner",
    "Tool Maker",
    "Tour Guide",
    "Tower Technician",
    "Traffic Technician",
    "Train Conductor",
    "Training Manager",
    "Training Specialist",
    "Transit Bus Driver",
    "Transit Police Officer",
    "Transportation Inspector",
    "Transportation Manager",
    "Transportation Security Screener",
    "Travel Agent",
    "Travel Consultant",
    "Travel Nurse",
    "Tree Trimmer",
    "Truck Driver",
    "Truck Mechanic",
    "TSA Agent",
    "Tutor",
    "Typist",
    "UI Developer",
    "Ultrasound Technologist",
    "Umpire",
    "Underground General Labor",
    "Underground Miner",
    "Upholsterer",
    "UPS Package Handler",
    "Urban Planner",
    "Usher",
    "UX Designer",
    "Valve Technician",
    "Vascular Technologist",
    "Vehicle Cleaner",
    "Vending Machine Repairer",
    "Veterinary Technician",
    "VFX Producer",
    "Vice President",
    "Vice Principal",
    "Video Editor",
    "Video Technician",
    "Vinyl Production Worker",
    "Virtual Assistant",
    "Virtual Events Manager",
    "Virtual Reality Developer",
    "Visual Basic Developer",
    "Visual Merchandiser",
    "Vocational Rehabilitation Counselor",
    "Waiter",
    "Warehouse Cleaner",
    "Warehouse Loader",
    "Warehouse Manager",
    "Warehouse Worker",
    "Wastewater Operator",
    "Watch Repair",
    "Watchmaker",
    "Water Transfer Technician",
    "Water Treatment Plant Operator",
    "Water Worker",
    "Wedding Stylist",
    "Welder",
    "Wet Utilities Laborer",
    "Wetland",
    "Wholesale Sales Representative",
    "Wildlife Biologist",
    "Wind Turbine Technician",
    "Window Installer",
    "Wine Taster",
    "Woodworker",
    "Writer",
    "X-ray Technician",
    "Yardmaster",
    "Yoga Instructor",
    "Zip Line Guide",
    "Zoologist",
]
