row_location_list = {
    "Canada": [
        "Calgary, Alberta, Canada",
        "Edmonton, Alberta, Canada",
        "Vancouver, British Columbia, Canada",
        "Winnipeg, Manitoba, Canada",
        "Fredericton, New Brunswick, Canada",
        "Moncton, New Brunswick, Canada",
        "St. John's, Newfoundland and Labrador, Canada",
        "Halifax, Nova Scotia, Canada",
        "Toronto, Ontario, Canada",
        "Ottawa, Ontario, Canada",
        "Charlottetown, Prince Edward Island, Canada",
        "Montreal, Quebec, Canada",
        "Quebec City, Quebec, Canada",
        "Regina, Saskatchewan, Canada",
        "Saskatoon, Saskatchewan, Canada",
        "Yellowknife, Northwest Territories, Canada",
        "Whitehorse, Yukon, Canada",
        "Iqaluit, Nunavut, Canada",
    ],
    "United Kingdom": [
        "Birmingham, England, United Kingdom",
        "Bristol, England, United Kingdom",
        "Leeds, England, United Kingdom",
        "Liverpool, England, United Kingdom",
        "London, England, United Kingdom",
        "Manchester, England, United Kingdom",
        "Newcastle, England, United Kingdom",
        "Sheffield, England, United Kingdom",
        "Edinburgh, Scotland, United Kingdom",
        "Glasgow, Scotland, United Kingdom",
        "Cardiff, Wales, United Kingdom",
        "Swansea, Wales, United Kingdom",
        "Belfast, Northern Ireland, United Kingdom",
        "Derry, Northern Ireland, United Kingdom",
    ],
    "Australia": [
        "Sydney, New South Wales, Australia",
        "Melbourne, Victoria, Australia",
        "Brisbane, Queensland, Australia",
        "Perth, Western Australia, Australia",
        "Adelaide, South Australia, Australia",
        "Gold Coast, Queensland, Australia",
        "Canberra, Australian Capital Territory, Australia",
        "Newcastle, New South Wales, Australia",
        "Central Coast, New South Wales, Australia",
        "Hobart, Tasmania, Australia",
        "Darwin, Northern Territory, Australia",
        "Sunshine Coast, Queensland, Australia",
    ],
    "France": [
        "Paris, Île-de-France, France",
        "Marseille, Provence-Alpes-Côte d'Azur, France",
        "Lyon, Auvergne-Rhône-Alpes, France",
        "Toulouse, Occitanie, France",
        "Nice, Provence-Alpes-Côte d'Azur, France",
        "Nantes, Pays de la Loire, France",
        "Strasbourg, Grand Est, France",
        "Montpellier, Occitanie, France",
        "Bordeaux, Nouvelle-Aquitaine, France",
        "Lille, Hauts-de-France, France",
        "Rennes, Brittany, France",
        "Reims, Grand Est, France",
        "Le Havre, Normandy, France",
        "Saint-Étienne, Auvergne-Rhône-Alpes, France",
        "Toulon, Provence-Alpes-Côte d'Azur, France",
        "Grenoble, Auvergne-Rhône-Alpes, France",
        "Dijon, Bourgogne-Franche-Comté, France",
        "Angers, Pays de la Loire, France",
        "Nîmes, Occitanie, France",
        "Villeurbanne, Auvergne-Rhône-Alpes, France",
        "France"
    ],

    "Germany": [
        "Berlin, Berlin, Germany",
        "Hamburg, Hamburg, Germany",
        "Munich, Bavaria, Germany",
        "Cologne, North Rhine-Westphalia, Germany",
        "Frankfurt, Hesse, Germany",
        "Stuttgart, Baden-Württemberg, Germany",
        "Düsseldorf, North Rhine-Westphalia, Germany",
        "Dortmund, North Rhine-Westphalia, Germany",
        "Essen, North Rhine-Westphalia, Germany",
        "Bremen, Bremen, Germany",
        "Dresden, Saxony, Germany",
        "Leipzig, Saxony, Germany",
        "Hanover, Lower Saxony, Germany",
        "Nuremberg, Bavaria, Germany",
        "Duisburg, North Rhine-Westphalia, Germany",
        "Bochum, North Rhine-Westphalia, Germany",
        "Wuppertal, North Rhine-Westphalia, Germany",
        "Bielefeld, North Rhine-Westphalia, Germany",
        "Bonn, North Rhine-Westphalia, Germany",
        "Mannheim, Baden-Württemberg, Germany",
        "Germany",
    ],

    "Japan": [
        "Tokyo, Tokyo Metropolis, Japan",
        "Yokohama, Kanagawa Prefecture, Japan",
        "Osaka, Osaka Prefecture, Japan",
        "Nagoya, Aichi Prefecture, Japan",
        "Sapporo, Hokkaido Prefecture, Japan",
        "Fukuoka, Fukuoka Prefecture, Japan",
        "Kawasaki, Kanagawa Prefecture, Japan",
        "Kobe, Hyōgo Prefecture, Japan",
        "Kyoto, Kyoto Prefecture, Japan",
        "Saitama, Saitama Prefecture, Japan",
        "Hiroshima, Hiroshima Prefecture, Japan",
        "Sendai, Miyagi Prefecture, Japan",
        "Chiba, Chiba Prefecture, Japan",
        "Kitakyushu, Fukuoka Prefecture, Japan",
        "Sakai, Osaka Prefecture, Japan",
        "Niigata, Niigata Prefecture, Japan",
        "Hamamatsu, Shizuoka Prefecture, Japan",
        "Shizuoka, Shizuoka Prefecture, Japan",
        "Kumamoto, Kumamoto Prefecture, Japan",
        "Okayama, Okayama Prefecture, Japan",
        "Japan",
    ],

    "Italy": [
        "Rome, Lazio, Italy",
        "Milan, Lombardy, Italy",
        "Naples, Campania, Italy",
        "Turin, Piedmont, Italy",
        "Palermo, Sicily, Italy",
        "Genoa, Liguria, Italy",
        "Bologna, Emilia-Romagna, Italy",
        "Florence, Tuscany, Italy",
        "Bari, Apulia, Italy",
        "Catania, Sicily, Italy",
        "Venice, Veneto, Italy",
        "Verona, Veneto, Italy",
        "Messina, Sicily, Italy",
        "Padua, Veneto, Italy",
        "Trieste, Friuli Venezia Giulia, Italy",
        "Brescia, Lombardy, Italy",
        "Prato, Tuscany, Italy",
        "Taranto, Apulia, Italy",
        "Reggio Calabria, Calabria, Italy",
        "Modena, Emilia-Romagna, Italy",
        "Italy",
    ],

    "Spain": [
        "Madrid, Madrid, Spain",
        "Barcelona, Catalonia, Spain",
        "Valencia, Valencia, Spain",
        "Sevilla, Andalusia, Spain",
        "Zaragoza, Aragon, Spain",
        "Málaga, Andalusia, Spain",
        "Murcia, Murcia, Spain",
        "Palma, Balearic Islands, Spain",
        "Las Palmas de Gran Canaria, Canary Islands, Spain",
        "Bilbao, Basque Country, Spain",
        "Alicante, Valencia, Spain",
        "Córdoba, Andalusia, Spain",
        "Valladolid, Castile and León, Spain",
        "Vigo, Galicia, Spain",
        "Gijón, Asturias, Spain",
        "L'Hospitalet de Llobregat, Catalonia, Spain",
        "A Coruña, Galicia, Spain",
        "Granada, Andalusia, Spain",
        "Elche, Valencia, Spain",
        "Oviedo, Asturias, Spain",
        "Spain",
    ],

    "Switzerland": [
        "Zurich, Zurich Canton, Switzerland",
        "Geneva, Geneva Canton, Switzerland",
        "Basel, Basel-Stadt Canton, Switzerland",
        "Bern, Bern Canton, Switzerland",
        "Lausanne, Vaud Canton, Switzerland",
        "Lucerne, Lucerne Canton, Switzerland",
        "St. Moritz, Graubünden Canton, Switzerland",
        "Lugano, Ticino Canton, Switzerland",
        "Neuchâtel, Neuchâtel Canton, Switzerland",
        "Zug, Zug Canton, Switzerland",
        "Switzerland",
    ],

    "Netherlands": [
        "Amsterdam, North Holland, Netherlands",
        "Rotterdam, South Holland, Netherlands",
        "The Hague (Den Haag), South Holland, Netherlands",
        "Utrecht, Utrecht, Netherlands",
        "Eindhoven, North Brabant, Netherlands",
        "Tilburg, North Brabant, Netherlands",
        "Groningen, Groningen, Netherlands",
        "Almere, Flevoland, Netherlands",
        "Breda, North Brabant, Netherlands",
        "Nijmegen, Gelderland, Netherlands",
        "Netherlands",
    ],

    "United Arab Emirates": [
        "Dubai, Dubai, United Arab Emirates",
        "Abu Dhabi, Abu Dhabi, United Arab Emirates",
        "Sharjah, Sharjah, United Arab Emirates",
        "Ajman, Ajman, United Arab Emirates",
        "Ras al-Khaimah, Ras al-Khaimah, United Arab Emirates",
        "Fujairah, Fujairah, United Arab Emirates",
        "Al Ain, Abu Dhabi, United Arab Emirates",
        "United Arab Emirates",
    ],

    "South Korea": [
        "Seoul, Seoul Special City, South Korea",
        "Busan, Busan Metropolitan City, South Korea",
        "Incheon, Incheon Metropolitan City, South Korea",
        "Daegu, Daegu Metropolitan City, South Korea",
        "Daejeon, Daejeon Metropolitan City, South Korea",
        "Gwangju, Gwangju Metropolitan City, South Korea",
        "Ulsan, Ulsan Metropolitan City, South Korea",
        "Suwon, Gyeonggi Province, South Korea",
        "Goyang, Gyeonggi Province, South Korea",
        "Yongin, Gyeonggi Province, South Korea",
        "Seongnam, Gyeonggi Province, South Korea",
        "Jeju City, Jeju Province, South Korea",
        "South Korea",
    ],

    "Sweden": [
        "Stockholm, Stockholm County, Sweden",
        "Gothenburg, Västra Götaland County, Sweden",
        "Malmö, Skåne County, Sweden",
        "Uppsala, Uppsala County, Sweden",
        "Västerås, Västmanland County, Sweden",
        "Örebro, Örebro County, Sweden",
        "Linköping, Östergötland County, Sweden",
        "Helsingborg, Skåne County, Sweden",
        "Jönköping, Jönköping County, Sweden",
        "Lund, Skåne County, Sweden",
        "Sweden",
    ],

    "Singapore": [
        "Singapore City, Central Region, Singapore",
        "Bedok, East Region, Singapore",
        "Bukit Batok, West Region, Singapore",
        "Bukit Merah, Central Region, Singapore",
        "Bukit Panjang, West Region, Singapore",
        "Clementi, West Region, Singapore",
        "Jurong East, West Region, Singapore",
        "Jurong West, West Region, Singapore",
        "Kallang, Central Region, Singapore",
        "Queenstown, Central Region, Singapore",
        "Toa Payoh, Central Region, Singapore",
        "Woodlands, North Region, Singapore",
        "Singapore"
    ],

    "Denmark": [
        "Copenhagen, Capital Region (Hovedstaden), Denmark",
        "Aarhus, Central Denmark Region (Midtjylland), Denmark",
        "Odense, Southern Denmark Region (Syddanmark), Denmark",
        "Aalborg, North Denmark Region (Nordjylland), Denmark",
        "Esbjerg, Southern Denmark Region (Syddanmark), Denmark",
        "Randers, Central Denmark Region (Midtjylland), Denmark",
        "Kolding, Southern Denmark Region (Syddanmark), Denmark",
        "Herning, Central Denmark Region (Midtjylland), Denmark",
        "Helsingør, Capital Region (Hovedstaden), Denmark",
        "Viborg, Central Denmark Region (Midtjylland), Denmark",
        "Denmark"
    ],

    "Belgium": [
        "Brussels, Brussels-Capital Region, Belgium",
        "Antwerp, Flanders, Belgium",
        "Ghent, Flanders, Belgium",
        "Bruges, Flanders, Belgium",
        "Liege, Wallonia, Belgium",
        "Charleroi, Wallonia, Belgium",
        "Namur, Wallonia, Belgium",
        "Leuven, Flanders, Belgium",
        "Mechelen, Flanders, Belgium",
        "Sint-Niklaas, Flanders, Belgium",
        "Belgium",
    ],

    "Portugal": [
        "Lisbon, Lisbon District, Portugal",
        "Oporto (Porto), Porto District, Portugal",
        "Vila Nova de Gaia, Porto District, Portugal",
        "Amadora, Lisbon District, Portugal",
        "Braga, Braga District, Portugal",
        "Coimbra, Coimbra District, Portugal",
        "Aveiro, Aveiro District, Portugal",
        "Setúbal, Setúbal District, Portugal",
        "Faro, Algarve Region, Portugal",
        "Évora, Évora District, Portugal",
        "Portugal",
    ],

    "Ireland": [
        "Dublin, Dublin City, Ireland",
        "Cork, County Cork, Ireland",
        "Limerick, County Limerick, Ireland",
        "Galway, County Galway, Ireland",
        "Waterford, County Waterford, Ireland",
        "Kilkenny, County Kilkenny, Ireland",
        "Sligo, County Sligo, Ireland",
        "Dundalk, County Louth, Ireland",
        "Drogheda, County Louth, Ireland",
        "Bray, County Wicklow, Ireland",
        "Ireland"
    ],

    "Norway": [
        "Oslo, Oslo County, Norway",
        "Bergen, Vestland County, Norway",
        "Stavanger, Rogaland County, Norway",
        "Trondheim, Trøndelag County, Norway",
        "Drammen, Viken County, Norway",
        "Fredrikstad, Viken County, Norway",
        "Porsgrunn, Vestfold og Telemark County, Norway",
        "Sandnes, Rogaland County, Norway",
        "Tromsø, Troms og Finnmark County, Norway",
        "Ålesund, Møre og Romsdal County, Norway",
        "Norway",
    ],

    "New Zealand": [
        "Auckland, Auckland Region, New Zealand",
        "Wellington, Wellington Region, New Zealand",
        "Christchurch, Canterbury Region, New Zealand",
        "Hamilton, Waikato Region, New Zealand",
        "Tauranga, Bay of Plenty Region, New Zealand",
        "Dunedin, Otago Region, New Zealand",
        "Palmerston North, Manawatū-Whanganui Region, New Zealand",
        "Napier-Hastings, Hawke's Bay Region, New Zealand",
        "Rotorua, Bay of Plenty Region, New Zealand",
        "Invercargill, Southland Region, New Zealand",
        "New Zealand",
    ],

    "Brazil": [
        "São Paulo, São Paulo, Brazil",
        "Rio de Janeiro, Rio de Janeiro, Brazil",
        "Brasília, Federal District, Brazil",
        "Salvador, Bahia, Brazil",
        "Fortaleza, Ceará, Brazil",
        "Belo Horizonte, Minas Gerais, Brazil",
        "Curitiba, Paraná, Brazil",
        "Recife, Pernambuco, Brazil",
        "Porto Alegre, Rio Grande do Sul, Brazil",
        "Manaus, Amazonas, Brazil",
        "Goiânia, Goiás, Brazil",
        "Belém, Pará, Brazil",
        "São Luís, Maranhão, Brazil",
        "Maceió, Alagoas, Brazil",
        "Natal, Rio Grande do Norte, Brazil",
        "Brazil"
    ],

    "Poland": [
        "Warsaw, Masovian Voivodeship, Poland",
        "Kraków, Lesser Poland Voivodeship, Poland",
        "Łódź, Łódź Voivodeship, Poland",
        "Wrocław, Lower Silesian Voivodeship, Poland",
        "Poznań, Greater Poland Voivodeship, Poland",
        "Gdańsk, Pomeranian Voivodeship, Poland",
        "Szczecin, West Pomeranian Voivodeship, Poland",
        "Bydgoszcz, Kuyavian-Pomeranian Voivodeship, Poland",
        "Lublin, Lublin Voivodeship, Poland",
        "Katowice, Silesian Voivodeship, Poland",
        "Białystok, Podlaskie Voivodeship, Poland",
        "Toruń, Kuyavian-Pomeranian Voivodeship, Poland",
        "Kielce, Świętokrzyskie Voivodeship, Poland",
        "Rzeszów, Subcarpathian Voivodeship, Poland",
        "Opole, Opole Voivodeship, Poland",
        "Poland"
    ],

    "Luxembourg": [
        "Luxembourg City, Luxembourg District, Luxembourg",
        "Esch-sur-Alzette, Luxembourg District, Luxembourg",
        "Differdange, Luxembourg District, Luxembourg",
        "Dudelange, Luxembourg District, Luxembourg",
        "Ettelbruck, Diekirch District, Luxembourg",
        "Wiltz, Diekirch District, Luxembourg",
        "Remich, Grevenmacher District, Luxembourg",
        "Mondorf-les-Bains, Grevenmacher District, Luxembourg",
        "Pétange, Luxembourg District, Luxembourg",
        "Clervaux, Diekirch District, Luxembourg",
        "Luxembourg",
    ],

    "India": [
        "Mumbai, Maharashtra, India",
        "Delhi, Delhi, India",
        "Bangalore, Karnataka, India",
        "Hyderabad, Telangana, India",
        "Ahmedabad, Gujarat, India",
        "Chennai, Tamil Nadu, India",
        "Kolkata, West Bengal, India",
        "Surat, Gujarat, India",
        "Pune, Maharashtra, India",
        "Jaipur, Rajasthan, India",
        "Lucknow, Uttar Pradesh, India",
        "Kanpur, Uttar Pradesh, India",
        "Nagpur, Maharashtra, India",
        "Indore, Madhya Pradesh, India",
        "Thane, Maharashtra, India",
        "Bhopal, Madhya Pradesh, India",
        "Vadodara, Gujarat, India",
        "Coimbatore, Tamil Nadu, India",
        "Patna, Bihar, India",
        "Agra, Uttar Pradesh, India",
        "India",
    ],

    "Greece": [
        "Athens, Attica, Greece",
        "Thessaloniki, Central Macedonia, Greece",
        "Patras, Western Greece, Greece",
        "Heraklion, Crete, Greece",
        "Larissa, Thessaly, Greece",
        "Volos, Thessaly, Greece",
        "Rhodes, South Aegean, Greece",
        "Ioannina, Epirus, Greece",
        "Chania, Crete, Greece",
        "Kalamata, Peloponnese, Greece",
        "Greece",
    ],

    "Finland": [
        "Helsinki, Uusimaa, Finland",
        "Espoo, Uusimaa, Finland",
        "Tampere, Pirkanmaa, Finland",
        "Vantaa, Uusimaa, Finland",
        "Oulu, North Ostrobothnia, Finland",
        "Turku, Southwest Finland, Finland",
        "Jyväskylä, Central Finland, Finland",
        "Lahti, Päijät-Häme, Finland",
        "Kuopio, North Savonia, Finland",
        "Pori, Satakunta, Finland",
        "Finland",
    ],

    "Turkey": [
        "Istanbul, Istanbul Province, Turkey",
        "Ankara, Ankara Province, Turkey",
        "Izmir, Izmir Province, Turkey",
        "Bursa, Bursa Province, Turkey",
        "Antalya, Antalya Province, Turkey",
        "Adana, Adana Province, Turkey",
        "Konya, Konya Province, Turkey",
        "Gaziantep, Gaziantep Province, Turkey",
        "Mersin, Mersin Province, Turkey",
        "Kayseri, Kayseri Province, Turkey",
        "Diyarbakır, Diyarbakır Province, Turkey",
        "Eskişehir, Eskişehir Province, Turkey",
        "Samsun, Samsun Province, Turkey",
        "Trabzon, Trabzon Province, Turkey",
        "Malatya, Malatya Province, Turkey",
        "Turkey",
    ],

    "Argentina": [
        "Buenos Aires, Buenos Aires Province, Argentina",
        "Córdoba, Córdoba Province, Argentina",
        "Rosario, Santa Fe Province, Argentina",
        "Mendoza, Mendoza Province, Argentina",
        "La Plata, Buenos Aires Province, Argentina",
        "San Miguel de Tucumán, Tucumán Province, Argentina",
        "Mar del Plata, Buenos Aires Province, Argentina",
        "Salta, Salta Province, Argentina",
        "Santa Fe, Santa Fe Province, Argentina",
        "Corrientes, Corrientes Province, Argentina",
        "Argentina",
    ],

    "Saudi Arabia": [
        "Riyadh, Riyadh Province, Saudi Arabia",
        "Jeddah, Makkah Province, Saudi Arabia",
        "Mecca (Makkah), Makkah Province, Saudi Arabia",
        "Dammam, Eastern Province, Saudi Arabia",
        "Khobar, Eastern Province, Saudi Arabia",
        "Medina (Madinah), Madinah Province, Saudi Arabia",
        "Dhahran, Eastern Province, Saudi Arabia",
        "Khamis Mushait, Asir Province, Saudi Arabia",
        "Abha, Asir Province, Saudi Arabia",
        "Jubail, Eastern Province, Saudi Arabia",
        "Saudi Arabia",
    ],

    "Qatar": [
        "Doha, Doha Municipality, Qatar",
        "Al Rayyan, Al Rayyan Municipality, Qatar",
        "Umm Salal, Umm Salal Municipality, Qatar",
        "Al Khor, Al Khor Municipality, Qatar",
        "Madinat ash Shamal, Madinat ash Shamal Municipality, Qatar",
        "Al Wakrah, Al Wakrah Municipality, Qatar",
        "Lusail, Al Daayen Municipality, Qatar",
        "Mesaieed, Al Wakrah Municipality, Qatar",
        "Qatar",
    ],

    "Mexico": [
        "Mexico City, Mexico City, Mexico",
        "Guadalajara, Jalisco, Mexico",
        "Monterrey, Nuevo León, Mexico",
        "Puebla, Puebla, Mexico",
        "León, Guanajuato, Mexico",
        "Tijuana, Baja California, Mexico",
        "Mérida, Yucatán, Mexico",
        "San Luis Potosí, San Luis Potosí, Mexico",
        "Querétaro, Querétaro, Mexico",
        "Culiacán, Sinaloa, Mexico",
        "Juárez, Chihuahua, Mexico",
        "Toluca, State of Mexico, Mexico",
        "Mexicali, Baja California, Mexico",
        "Hermosillo, Sonora, Mexico",
        "Morelia, Michoacán, Mexico",
        "Mexico",
    ],

    "South Africa": [
        "Johannesburg, Gauteng, South Africa",
        "Cape Town, Western Cape, South Africa",
        "Durban, KwaZulu-Natal, South Africa",
        "Pretoria, Gauteng, South Africa",
        "Port Elizabeth (Gqeberha), Eastern Cape, South Africa",
        "Bloemfontein, Free State, South Africa",
        "East London, Eastern Cape, South Africa",
        "Rustenburg, North West, South Africa",
        "Kimberley, Northern Cape, South Africa",
        "Polokwane, Limpopo, South Africa",
        "South Africa"
    ],

    "Thailand": [
        "Bangkok, Bangkok Metropolis, Thailand",
        "Nonthaburi, Nonthaburi Province, Thailand",
        "Nakhon Ratchasima (Korat), Nakhon Ratchasima Province, Thailand",
        "Chiang Mai, Chiang Mai Province, Thailand",
        "Hat Yai, Songkhla Province, Thailand",
        "Udon Thani, Udon Thani Province, Thailand",
        "Khon Kaen, Khon Kaen Province, Thailand",
        "Pattaya, Chonburi Province, Thailand",
        "Samut Prakan, Samut Prakan Province, Thailand",
        "Nakhon Si Thammarat, Nakhon Si Thammarat Province, Thailand",
        "Thailand",
    ],

    "Israel": [
        "Jerusalem, Jerusalem District, Israel",
        "Tel Aviv, Tel Aviv District, Israel",
        "Haifa, Haifa District, Israel",
        "Rishon Lezion, Central District, Israel",
        "Petah Tikva, Central District, Israel",
        "Ashdod, Southern District, Israel",
        "Ashkelon, Southern District, Israel",
        "Be'er Sheva, Southern District, Israel",
        "Netanya, Central District, Israel",
        "Herzliya, Central District, Israel",
        "Israel",
    ],

    "Czechia": [
        "Prague (Praha), Prague, Czechia",
        "Brno, South Moravian Region, Czechia",
        "Ostrava, Moravian-Silesian Region, Czechia",
        "Plzeň, Plzeň Region, Czechia",
        "Liberec, Liberec Region, Czechia",
        "Hradec Králové, Hradec Králové Region, Czechia",
        "Ústí nad Labem, Ústí nad Labem Region, Czechia",
        "Pardubice, Pardubice Region, Czechia",
        "Zlin, Zlin Region, Czechia",
        "Jihlava, Vysočina Region, Czechia",
        "Czechia",
    ],

    "Hungary": [
        "Budapest, Budapest Capital District, Hungary",
        "Debrecen, Hajdú-Bihar County, Hungary",
        "Szeged, Csongrád-Csanád County, Hungary",
        "Miskolc, Borsod-Abaúj-Zemplén County, Hungary",
        "Pécs, Baranya County, Hungary",
        "Győr, Győr-Moson-Sopron County, Hungary",
        "Nyíregyháza, Szabolcs-Szatmár-Bereg County, Hungary",
        "Kecskemét, Bács-Kiskun County, Hungary",
        "Szombathely, Vas County, Hungary",
        "Eger, Heves County, Hungary",
        "Hungary",
    ],

    "Croatia": [
        "Zagreb, City of Zagreb, Croatia",
        "Split, Split-Dalmatia County, Croatia",
        "Rijeka, Primorje-Gorski Kotar County, Croatia",
        "Osijek, Osijek-Baranja County, Croatia",
        "Zadar, Zadar County, Croatia",
        "Pula, Istria County, Croatia",
        "Varaždin, Varaždin County, Croatia",
        "Šibenik, Šibenik-Knin County, Croatia",
        "Karlovac, Karlovac County, Croatia",
        "Sisak, Sisak-Moslavina County, Croatia",
        "Croatia",
    ],

    "Malaysia": [
        "Kuala Lumpur, Federal Territory of Kuala Lumpur, Malaysia",
        "George Town, Penang, Malaysia",
        "Johor Bahru, Johor, Malaysia",
        "Ipoh, Perak, Malaysia",
        "Klang, Selangor, Malaysia",
        "Shah Alam, Selangor, Malaysia",
        "Kuala Terengganu, Terengganu, Malaysia",
        "Melaka (Malacca), Melaka, Malaysia",
        "Kota Kinabalu, Sabah, Malaysia",
        "Kuching, Sarawak, Malaysia",
        "Malaysia",
    ],

    "Egypt": [
        "Cairo, Cairo Governorate, Egypt",
        "Alexandria, Alexandria Governorate, Egypt",
        "Giza, Giza Governorate, Egypt",
        "Shubra El Kheima, Qalyubia Governorate, Egypt",
        "Port Said, Port Said Governorate, Egypt",
        "Suez, Suez Governorate, Egypt",
        "Luxor, Luxor Governorate, Egypt",
        "Aswan, Aswan Governorate, Egypt",
        "Mansoura, Dakahlia Governorate, Egypt",
        "Tanta, Gharbia Governorate, Egypt",
        "Egypt",
    ],

    "Romania": [
        "Bucharest, Bucharest Municipality, Romania",
        "Cluj-Napoca, Cluj County, Romania",
        "Timișoara, Timiș County, Romania",
        "Iași, Iași County, Romania",
        "Constanța, Constanța County, Romania",
        "Craiova, Dolj County, Romania",
        "Brașov, Brașov County, Romania",
        "Galați, Galați County, Romania",
        "Ploiești, Prahova County, Romania",
        "Oradea, Bihor County, Romania",
        "Romania"
    ],

    "Philippines": [
        "Quezon City, National Capital Region (NCR), Philippines",
        "Manila, National Capital Region (NCR), Philippines",
        "Caloocan, National Capital Region (NCR), Philippines",
        "Davao City, Davao Region, Philippines",
        "Cebu City, Central Visayas (Region VII), Philippines",
        "Zamboanga City, Zamboanga Peninsula (Region IX), Philippines",
        "Taguig, National Capital Region (NCR), Philippines",
        "Antipolo, Calabarzon (Region IV-A), Philippines",
        "Pasig, National Capital Region (NCR), Philippines",
        "Cagayan de Oro, Northern Mindanao (Region X), Philippines",
        "Philippines"
    ],

    "Panama": [
        "Panama City, Panama Province, Panama",
        "San Miguelito, Panama Province, Panama",
        "Colón, Colón Province, Panama",
        "David, Chiriquí Province, Panama",
        "La Chorrera, Panama Province, Panama",
        "Santiago, Veraguas Province, Panama",
        "Aguadulce, Coclé Province, Panama",
        "Penonomé, Coclé Province, Panama",
        "El Chorrillo, Panama Province, Panama",
        "Bocas del Toro, Bocas del Toro Province, Panama",
        "Panama",
    ],

    "Bulgaria": [
        "Sofia, Sofia City Province, Bulgaria",
        "Plovdiv, Plovdiv Province, Bulgaria",
        "Varna, Varna Province, Bulgaria",
        "Burgas, Burgas Province, Bulgaria",
        "Ruse, Ruse Province, Bulgaria",
        "Stara Zagora, Stara Zagora Province, Bulgaria",
        "Pleven, Pleven Province, Bulgaria",
        "Dobrich, Dobrich Province, Bulgaria",
        "Sliven, Sliven Province, Bulgaria",
        "Shumen, Shumen Province, Bulgaria",
        "Bulgaria"
    ],

    "Indonesia": [
        "Jakarta, Jakarta Special Capital Region, Indonesia",
        "Surabaya, East Java, Indonesia",
        "Bandung, West Java, Indonesia",
        "Medan, North Sumatra, Indonesia",
        "Semarang, Central Java, Indonesia",
        "Makassar, South Sulawesi, Indonesia",
        "Palembang, South Sumatra, Indonesia",
        "Batam, Riau Islands, Indonesia",
        "Yogyakarta, Special Region of Yogyakarta, Indonesia",
        "Denpasar, Bali, Indonesia",
        "Indonesia",
    ],

    "Vietnam": [
        "Ho Chi Minh City, Ho Chi Minh City Municipality, Vietnam",
        "Hanoi, Hanoi Municipality, Vietnam",
        "Da Nang, Da Nang Municipality, Vietnam",
        "Hai Phong, Hai Phong Municipality, Vietnam",
        "Can Tho, Can Tho Municipality, Vietnam",
        "Bien Hoa, Dong Nai Province, Vietnam",
        "Nha Trang, Khanh Hoa Province, Vietnam",
        "Hue, Thua Thien-Hue Province, Vietnam",
        "Vinh, Nghe An Province, Vietnam",
        "Quy Nhon, Binh Dinh Province, Vietnam",
        "Vietnam",
    ],

    "Chile": [
        "Santiago, Santiago Metropolitan Region, Chile",
        "Valparaíso, Valparaíso Region, Chile",
        "Concepción, Biobío Region, Chile",
        "Antofagasta, Antofagasta Region, Chile",
        "Temuco, La Araucanía Region, Chile",
        "Rancagua, O'Higgins Region, Chile",
        "Iquique, Tarapacá Region, Chile",
        "La Serena, Coquimbo Region, Chile",
        "Chillán, Biobío Region, Chile",
        "Arica, Arica and Parinacota Region, Chile",
        "Chile",
    ],

    "Slovakia": [
        "Bratislava, Bratislava Region, Slovakia",
        "Košice, Košice Region, Slovakia",
        "Prešov, Prešov Region, Slovakia",
        "Nitra, Nitra Region, Slovakia",
        "Žilina, Žilina Region, Slovakia",
        "Trenčín, Trenčín Region, Slovakia",
        "Martin, Žilina Region, Slovakia",
        "Poprad, Prešov Region, Slovakia",
        "Bratislava, Bratislava Region, Slovakia",
        "Piešťany, Trnava Region, Slovakia",
        "Slovakia"
    ],

    "Colombia": [
        "Bogotá, Bogotá D.C., Colombia",
        "Medellín, Antioquia Department, Colombia",
        "Cali, Valle del Cauca Department, Colombia",
        "Barranquilla, Atlántico Department, Colombia",
        "Cartagena, Bolívar Department, Colombia",
        "Bucaramanga, Santander Department, Colombia",
        "Pereira, Risaralda Department, Colombia",
        "Santa Marta, Magdalena Department, Colombia",
        "Cúcuta, Norte de Santander Department, Colombia",
        "Ibagué, Tolima Department, Colombia",
        "Colombia",
    ],

    "Slovenia": [
        "Ljubljana, Ljubljana Statistical Region, Slovenia",
        "Maribor, Drava Statistical Region, Slovenia",
        "Celje, Savinja Statistical Region, Slovenia",
        "Kranj, Gorenjska Statistical Region, Slovenia",
        "Velenje, Savinja Statistical Region, Slovenia",
        "Novo Mesto, Southeast Slovenia Statistical Region, Slovenia",
        "Ptuj, Drava Statistical Region, Slovenia",
        "Kamnik, Central Slovenia Statistical Region, Slovenia",
        "Murska Sobota, Pomurska Statistical Region, Slovenia",
        "Trbovlje, Zasavska Statistical Region, Slovenia",
        "Slovenia",
    ],

    "Lithuania": [
        "Vilnius, Vilnius County, Lithuania",
        "Kaunas, Kaunas County, Lithuania",
        "Klaipėda, Klaipėda County, Lithuania",
        "Šiauliai, Šiauliai County, Lithuania",
        "Panevėžys, Panevėžys County, Lithuania",
        "Alytus, Alytus County, Lithuania",
        "Marijampolė, Marijampolė County, Lithuania",
        "Telšiai, Telšiai County, Lithuania",
        "Utena, Utena County, Lithuania",
        "Tauragė, Tauragė County, Lithuania",
        "Lithuania",
    ],

    "Estonia": [
        "Tallinn, Harju County, Estonia",
        "Tartu, Tartu County, Estonia",
        "Narva, Ida-Viru County, Estonia",
        "Kohtla-Järve, Ida-Viru County, Estonia",
        "Pärnu, Pärnu County, Estonia",
        "Rakvere, Lääne-Viru County, Estonia",
        "Viljandi, Viljandi County, Estonia",
        "Jõhvi, Ida-Viru County, Estonia",
        "Paide, Järva County, Estonia",
        "Kärdla, Hiiumaa County, Estonia",
        "Estonia",
    ],

    "Bahrain": [
        "Manama, Capital Governorate, Bahrain",
        "Muharraq, Muharraq Governorate, Bahrain",
        "Riffa, Southern Governorate, Bahrain",
        "Hamad Town, Northern Governorate, Bahrain",
        "A'ali, Northern Governorate, Bahrain",
        "Sitra, Capital Governorate, Bahrain",
        "Budaiya, Northern Governorate, Bahrain",
        "Isa Town, Southern Governorate, Bahrain",
        "Juffair, Capital Governorate, Bahrain",
        "Saar, Northern Governorate, Bahrain",
        "Bahrain"
    ],

    "Latvia": [
        "Riga, Riga Region, Latvia",
        "Daugavpils, Latgale Region, Latvia",
        "Liepāja, Kurzeme Region, Latvia",
        "Jelgava, Zemgale Region, Latvia",
        "Rēzekne, Latgale Region, Latvia",
        "Ventspils, Kurzeme Region, Latvia",
        "Jūrmala, Riga Region, Latvia",
        "Ogre, Riga Region, Latvia",
        "Salaspils, Riga Region, Latvia",
        "Tukums, Kurzeme Region, Latvia",
        "Latvia"
    ],

    "Cyprus": [
        "Nicosia, Nicosia District, Cyprus",
        "Limassol, Limassol District, Cyprus",
        "Larnaca, Larnaca District, Cyprus",
        "Famagusta, Famagusta District, Cyprus",
        "Paphos, Paphos District, Cyprus",
        "Kyrenia, Kyrenia District, Cyprus",
        "Paralimni, Famagusta District, Cyprus",
        "Protaras, Famagusta District, Cyprus",
        "Dali, Nicosia District, Cyprus",
        "Polis Chrysochous, Paphos District, Cyprus",
        "Cyprus"
    ],

    "Morocco": [
        "Casablanca, Casablanca-Settat, Morocco",
        "Rabat, Rabat-Salé-Kénitra, Morocco",
        "Fes, Fes-Meknes, Morocco",
        "Tangier, Tangier-Tetouan-Al Hoceima, Morocco",
        "Marrakesh, Marrakesh-Safi, Morocco",
        "Agadir, Souss-Massa, Morocco",
        "Salé, Rabat-Salé-Kénitra, Morocco",
        "Oujda, Oriental, Morocco",
        "Tétouan, Tangier-Tetouan-Al Hoceima, Morocco",
        "Meknes, Fes-Meknes, Morocco",
        "Morocco"
    ],

    "Costa Rica": [
        "San José, San José Province, Costa Rica",
        "Alajuela, Alajuela Province, Costa Rica",
        "Cartago, Cartago Province, Costa Rica",
        "Heredia, Heredia Province, Costa Rica",
        "Limón, Limón Province, Costa Rica",
        "Liberia, Guanacaste Province, Costa Rica",
        "San Isidro de El General, Pérez Zeledón Canton, San José Province, "
        "Costa Rica",
        "Puntarenas, Puntarenas Province, Costa Rica",
        "Esparza, Puntarenas Province, Costa Rica",
        "San Ramón, Alajuela Province, Costa Rica",
        "Costa Rica"
    ],

    "Uruguay": [
        "Montevideo, Montevideo Department, Uruguay",
        "Salto, Salto Department, Uruguay",
        "Paysandú, Paysandú Department, Uruguay",
        "Ciudad de la Costa, Canelones Department, Uruguay",
        "Rivera, Rivera Department, Uruguay",
        "Tacuarembó, Tacuarembó Department, Uruguay",
        "Maldonado, Maldonado Department, Uruguay",
        "Durazno, Durazno Department, Uruguay",
        "San José de Mayo, San José Department, Uruguay",
        "Minas, Lavalleja Department, Uruguay",
        "Uruguay"
    ],

    "Serbia": [
        "Belgrade, Belgrade District, Serbia",
        "Novi Sad, South Bačka District, Serbia",
        "Niš, Nišava District, Serbia",
        "Kragujevac, Šumadija District, Serbia",
        "Subotica, North Bačka District, Serbia",
        "Zrenjanin, Central Banat District, Serbia",
        "Šabac, Mačva District, Serbia",
        "Pancevo, South Banat District, Serbia",
        "Kraljevo, Raška District, Serbia",
        "Užice, Zlatibor District, Serbia",
        "Serbia"
    ],

    "Jordan": [
        "Amman, Amman Governorate, Jordan",
        "Zarqa, Zarqa Governorate, Jordan",
        "Irbid, Irbid Governorate, Jordan",
        "Aqaba, Aqaba Governorate, Jordan",
        "Ma'an, Ma'an Governorate, Jordan",
        "Madaba, Madaba Governorate, Jordan",
        "Karak, Karak Governorate, Jordan",
        "Salt, Balqa Governorate, Jordan",
        "Jerrash, Jerash Governorate, Jordan",
        "Rusaifa, Zarqa Governorate, Jordan",
        "Jordan"
    ],

    "Tunisia": [
        "Tunis, Tunis Governorate, Tunisia",
        "Sfax, Sfax Governorate, Tunisia",
        "Sousse, Sousse Governorate, Tunisia",
        "Kairouan, Kairouan Governorate, Tunisia",
        "Bizerte, Bizerte Governorate, Tunisia",
        "Gabès, Gabès Governorate, Tunisia",
        "Monastir, Monastir Governorate, Tunisia",
        "La Goulette, Tunis Governorate, Tunisia",
        "Zarzis, Medenine Governorate, Tunisia",
        "Hammamet, Nabeul Governorate, Tunisia",
        "Tunisia"
    ],

    "Dominican Republic": [
        "Santo Domingo, Distrito Nacional, Dominican Republic",
        "Santiago de los Caballeros, Santiago Province, Dominican Republic",
        "La Romana, La Romana Province, Dominican Republic",
        "San Pedro de Macorís, San Pedro de Macorís Province, Dominican "
        "Republic",
        "Puerto Plata, Puerto Plata Province, Dominican Republic",
        "Higüey, La Altagracia Province, Dominican Republic",
        "San Francisco de Macorís, Duarte Province, Dominican Republic",
        "Moca, Espaillat Province, Dominican Republic",
        "Baní, Peravia Province, Dominican Republic",
        "Mao, Valverde Province, Dominican Republic",
        "Dominican Republic"
    ],

    "Ecuador": [
        "Quito, Pichincha Province, Ecuador",
        "Guayaquil, Guayas Province, Ecuador",
        "Cuenca, Azuay Province, Ecuador",
        "Santo Domingo, Santo Domingo de los Tsáchilas Province, Ecuador",
        "Manta, Manabí Province, Ecuador",
        "Portoviejo, Manabí Province, Ecuador",
        "Loja, Loja Province, Ecuador",
        "Ambato, Tungurahua Province, Ecuador",
        "Machala, El Oro Province, Ecuador",
        "Esmeraldas, Esmeraldas Province, Ecuador",
        "Ecuador"
    ],

    "Peru": [
        "Lima, Lima Region, Peru",
        "Arequipa, Arequipa Region, Peru",
        "Trujillo, La Libertad Region, Peru",
        "Callao, Callao Region, Peru",
        "Chiclayo, Lambayeque Region, Peru",
        "Piura, Piura Region, Peru",
        "Iquitos, Loreto Region, Peru",
        "Cusco, Cusco Region, Peru",
        "Huancayo, Junín Region, Peru",
        "Puno, Puno Region, Peru",
        "Peru"
    ],

    "Oman": [
        "Muscat, Muscat Governorate, Oman",
        "Salalah, Dhofar Governorate, Oman",
        "Sohar, North Batinah Governorate, Oman",
        "Nizwa, Ad Dakhiliyah Governorate, Oman",
        "Sur, Ash Sharqiyah Governorate, Oman",
        "Ibra, Ash Sharqiyah Governorate, Oman",
        "Buraimi, Al Buraimi Governorate, Oman",
        "Khasab, Musandam Governorate, Oman",
        "Rustaq, Ad Dakhiliyah Governorate, Oman",
        "Dibba Al-Baya, Musandam Governorate, Oman",
        "Oman"
    ],

    "Algeria": [
        "Algiers, Algiers Province, Algeria",
        "Oran, Oran Province, Algeria",
        "Constantine, Constantine Province, Algeria",
        "Annaba, Annaba Province, Algeria",
        "Blida, Blida Province, Algeria",
        "Setif, Setif Province, Algeria",
        "Batna, Batna Province, Algeria",
        "Bejaia, Bejaia Province, Algeria",
        "Tlemcen, Tlemcen Province, Algeria",
        "El Oued, El Oued Province, Algeria",
        "Algeria",
    ],

    "Sri Lanka": [
        "Colombo, Western Province, Sri Lanka",
        "Kandy, Central Province, Sri Lanka",
        "Galle, Southern Province, Sri Lanka",
        "Jaffna, Northern Province, Sri Lanka",
        "Negombo, Western Province, Sri Lanka",
        "Trincomalee, Eastern Province, Sri Lanka",
        "Batticaloa, Eastern Province, Sri Lanka",
        "Anuradhapura, North Central Province, Sri Lanka",
        "Matara, Southern Province, Sri Lanka",
        "Ratnapura, Sabaragamuwa Province, Sri Lanka",
        "Sri Lanka"
    ],
}
