company_list = [
    "24-7 Intouch",
    "3Play Media",
    "ABC",
    "ABC Consultants",
    "ACI Worldwide",
    "ADP",
    "ALDI",
    "AMC Theatres",
    "APTask",
    "ASAP",
    "AT&T",
    "Accenture",
    "Adobe",
    "Advanced Call Center",
    "Advantmed",
    "Aikegen",
    "Aira",
    "Airbnb",
    "Airbus",
    "Allied Universal",
    "Alphabet",
    "Amazon",
    "Amazon DSP",
    "Amazon Flex",
    "Amazon Warehouse",
    "Amazon Web Services",
    "Amelia",
    "American Express",
    "Anthology",
    "AppFolio",
    "Appen",
    "Apple",
    "Applied Intuition",
    "Aspen RXHealth",
    "Aspira",
    "Asurion",
    "Atlassian",
    "Audible",
    "AutoZone",
    "Avidxchange",
    "Baidu",
    "BAE Systems USA",
    "BDO",
    "BNY",
    "BairesDev",
    "BambooHR",
    "Bank of America",
    "Barclays",
    "Barnes & Noble",
    "Bath & Body Works",
    "Belcan",
    "Bentley Systems",
    "Best Buy",
    "Blackbaud",
    "Blackrock",
    "Block",
    "Bloomberg",
    "Boehringer Ingelheim",
    "Boeing",
    "Bristol Myers Squibb",
    "BroadPath",
    "Broadridge",
    "Buc-ee's",
    "Burger King",
    "Burlington Stores",
    "CLEAR",
    "COMTEC Information Systems",
    "CVS Health",
    "Calendly",
    "Capgemini",
    "Capital One",
    "Carahsoft Technology",
    "Catalyte",
    "Check Point Software Technologies",
    "Chick-fil-A Corporate",
    "Chili's",
    "Chipotle Mexican Grill",
    "Cintas",
    "Cisco",
    "Citadel",
    "Citi",
    "CLICKUP",
    "Clickworker",
    "CoStar Group",
    "Cognizant Technology Solutions",
    "Coinbase",
    "Colgate-Palmolive",
    "Collective Health",
    "Comcast",
    "Commvault",
    "Compass",
    "Concentrix",
    "ConnectWise",
    "Continental",
    "Corporate Tools",
    "Costco Wholesale",
    "Cotivti",
    "Cracker Barrel",
    "CrowdStrike",
    "Cvent",
    "DHL",
    "DHL Express",
    "DHL Group",
    "DICK'S Sporting Goods",
    "DONE by NONE",
    "DaVita",
    "Daily Transcription",
    "Dairy Queen",
    "Dandy",
    "Dassault Systèmes",
    "Datadog",
    "Datavant",
    "Dell Technologies",
    "Deloitte",
    "Delta Air Lines",
    "Deltek",
    "Dexian",
    "Diebold Nixdorf",
    "Dollar General",
    "Dollar Tree",
    "Domino's",
    "DoorDash",
    "Drake Software",
    "Dream Team",
    "Dropoff",
    "Dunkin'",
    "Dutch Bros Coffee",
    "EPAM Systems",
    "EXL",
    "EY",
    "Elastic",
    "Elevance Health",
    "Eli Lilly and Company",
    "Entrata",
    "Epic",
    "Epic Games",
    "Equinix",
    "Ericsson-Worldwide",
    "Esri",
    "Etsy",
    "Expedia Group",
    "FPT Software",
    "Factset",
    "Family Dollar",
    "FanDuel",
    "Fancy Hands",
    "Favor",
    "FedEx",
    "Fidelity Investments",
    "Five Below",
    "FloQast",
    "Food Lion",
    "Freelancer",
    "Frito-Lay",
    "Frontline Education",
    "GE",
    "GEP",
    "GitLab",
    "Glassdoor",
    "Globant",
    "Globe Life",
    "Goldman Sachs",
    "Goodwill Industries",
    "Google",
    "Grover Gaming",
    "Grubhub",
    "HCLTech",
    "HEB",
    "HealthSnap",
    "Healthmap Solutions",
    "Hewlett Packard",
    "Hexagon",
    "Hinge Health",
    "Hobby Lobby",
    "Honeywell",
    "HopSkipDrive",
    "Hudi",
    "Hulu",
    "IBM",
    "IDEMIA",
    "IGT Solutions",
    "INgram Micro",
    "IQor",
    "In-N-Out Burger",
    "Indeed",
    "Infosys",
    "Innodata",
    "Inovalon",
    "Intel",
    "Intuit",
    "Invisible Technologies",
    "J.P. Morgan",
    "Jane Street",
    "Johnson & Johnson",
    "JPMorgan Chase Co",
    "Kaiser Permanente",
    "KPMG",
    "Kohl's",
    "Kraft Heinz",
    "Kroger",
    "L3Harris",
    "Labcorp",
    "LanceSoft",
    "LeadVenture",
    "LexisNexis Legal Professional",
    "LinkedIn",
    "Lowe's Home Improvement",
    "LTIMindtree",
    "Lumen",
    "M.C. Dean",
    "Macy's",
    "Manhattan Associates",
    "Marriott International",
    "Marshalls",
    "Mastercard",
    "MathWorks",
    "McDonald's",
    "McKinsey & Company",
    "Medidata Solutions",
    "Medtronic",
    "Meijer",
    "Memorial Sloan Kettering Cancer Center",
    "Menards",
    "Meta",
    "Microsoft",
    "Microworkers",
    "Mindbody",
    "Mitchell International",
    "Mitratech",
    "Moderna",
    "ModSquad",
    "MongoDB",
    "Molex",
    "Morgan Stanley",
    "Motive",
    "Mphasis",
    "NBCUniversal",
    "NCR",
    "New York Life",
    "New York Times",
    "NimbleRx",
    "Nintendo",
    "Nomi Health",
    "Nordstrom",
    "Northrop Grumman",
    "Northwestern Mutual",
    "NVIDIA",
    "O'Reilly Auto Parts",
    "Okta",
    "Olive Garden",
    "OneSupport",
    "Opex",
    "Optum",
    "Oracle",
    "Outlier AI",
    "Oxford Global Resources",
    "PKIT Technologies",
    "PLAYTECH",
    "Pacific Gas and Electric Company",
    "Pacific Office Automation",
    "Palantir Technologies",
    "Panera Bread",
    "Paramount",
    "Paychex",
    "Paycom",
    "Paycor",
    "Paylocity",
    "Peloton Interactive",
    "PepsiCo",
    "PetSmart",
    "Pizza Hut",
    "Planet Fitness",
    "Podium",
    "Prime Systems",
    "Procter & Gamble",
    "Prudential",
    "Publicis Sapient",
    "Publix",
    "PwC",
    "Qualcomm",
    "Quickbox Fulfillment",
    "REPS",
    "RTZ Systems",
    "RWE",
    "Raising Cane's",
    "Red Ventures",
    "Regeneron",
    "Renaissance Learning",
    "Rev",
    "Revature",
    "Rocket Software",
    "Rockstar Games",
    "Ross Dress For Less",
    "SAP",
    "SHEIN",
    "SIXT",
    "SP Global",
    "Sage",
    "Salesforce",
    "Sam's Club",
    "Scale AI",
    "ScanScape",
    "Scylla",
    "SelfEmployed.com",
    "Semrush",
    "ServiceNow",
    "Shopify",
    "Siemens",
    "Siemens Digital Industries Software",
    "Sittercity",
    "Slack",
    "Smartsheet",
    "Smith.ai",
    "Solera",
    "Sonic Drive-In",
    "Spectraforce Technologies",
    "Spectrum",
    "SpotOn",
    "Spotify",
    "Starbucks",
    "Stellantis",
    "Stripe",
    "Synchrony",
    "Sysco",
    "TD SYNNEX",
    "TEKsystems",
    "TELUS International",
    "TJ Maxx",
    "TORC Robotics",
    "TSA Transportation Security Administration",
    "Taco Bell",
    "Takeda",
    "Target",
    "TaskRabbit",
    "Tata Consultancy Services",
    "Tata Consultancy Services North America",
    "Tech Mahindra",
    "Teemwork.ai",
    "Teleperformance",
    "Tencent",
    "Tesla",
    "Test",
    "Texas Roadhouse",
    "Text121chat",
    "The Cigna Group",
    "The Coca-Cola Company",
    "The Home Depot",
    "Thomson Reuters",
    "Toast",
    "Tractor Supply",
    "Trader Joe's",
    "TranscribeMe",
    "Travelers",
    "Trimble",
    "Turbo Debt",
    "Two Sigma",
    "Tyler Technologies",
    "Tyson Foods",
    "U.S. Army",
    "UBS",
    "UKG",
    "UPS",
    "US Veterans",
    "Uber",
    "UberEATS",
    "Ulta",
    "United States Postal Service",
    "UnitedHealth Group",
    "Valve",
    "Varonis Systems",
    "Vector Marketing",
    "Veeva Systems",
    "Verisk",
    "Verisma Systems",
    "Verizon",
    "Verkada",
    "Vertafore",
    "Vertex Pharmaceuticals",
    "Visa",
    "Vyne",
    "WIS International",
    "Walt Disney Company",
    "Walgreens",
    "Walmart",
    "Warner Bros. Discovery",
    "Wells Fargo",
    "Welocalize",
    "Wendy's",
    "Wework",
    "Whole Foods Market",
    "Whova",
    "Wipro",
    "Wolters Kluwer",
    "Workday",
    "Xerox",
    "XiFin",
    "Xplor Technologies",
    "Xylem",
    "YASH Technologies",
    "YMCA",
    "Yahoo",
    "Yardi Systems",
    "Yelp",
    "Yext",
    "YouTube",
    "Zebra Technologies",
    "Zoom",
    "ZoomInfo",
    "apnTech",
    "brightwheel",
    "i3 Verticals",
    "iCIMS",
    "imprint",
    "isolved",
    "Ørsted",
]
