top_job_titles = [
    "Full Stack Engineer",
    "Front-End Engineer",
    "Backend Engineer",
    "Cybersecurity",
    "Software Engineer",
    "Software Developer",
    "UX/UI Designer",
    "MERN Developer",
    "Python Developer",
    "Javascript Developer",
    "Angular Developer",
    "React Developer",
    "React Native Developer",
    "Go Developer",
    "Golang Developer",
    "Rust Developer",
    ".NET Developer",
    "Web Developer",
    "Android Developer",
    "C Developer",
    "C# Developer",
    "C++ Developer",
    "iOS Developer",
    "Java Developer",
    "Mobile Application Developer",
    "Node.js Developer",
    "SQL Developer",
    "TypeScript Developer",
]
