top_location_list = {
    "Remote": [
        "Remote"
    ],
    "United States": [
        "San Francisco, California, United States",
        "New York City, New York, United States",
        "San Jose, California, United States",
        "Los Angeles, California, United States",
        "San Diego, California, United States",
        "Washington, D.C., United States",
        "Miami, Florida, United States",
        "Tampa, Florida, United States",

        "Austin, Texas, United States",
        "Houston, Texas, United States",
        "Dallas, Texas, United States",
        "Atlanta, Georgia, United States",
        "Sacramento, California, United States",

        "Birmingham, Alabama, United States",
        "Montgomery, Alabama, United States",
        "Anchorage, Alaska, United States",
        "Juneau, Alaska, United States",
        "Chandler, Arizona, United States",
        "Gilbert, Arizona, United States",
        "Mesa, Arizona, United States",
        "Phoenix, Arizona, United States",
        "Tucson, Arizona, United States",
        "Little Rock, Arkansas, United States",
        "Anaheim, California, United States",
        "Bakersfield, California, United States",
        "Fresno, California, United States",
        "Irvine, California, United States",
        "Long Beach, California, United States",
        "Oakland, California, United States",
        "Riverside, California, United States",
        "Santa Ana, California, United States",
        "Stockton, California, United States",
        "Aurora, Colorado, United States",
        "Colorado Springs, Colorado, United States",
        "Denver, Colorado, United States",
        "Bridgeport, Connecticut, United States",
        "Hartford, Connecticut, United States",
        "Dover, Delaware, United States",
        "Wilmington, Delaware, United States",
        "Jacksonville, Florida, United States",
        "Orlando, Florida, United States",
        "Tallahassee, Florida, United States",
        "Honolulu, Hawaii, United States",
        "Boise, Idaho, United States",
        "Chicago, Illinois, United States",
        "Springfield, Illinois, United States",
        "Indianapolis, Indiana, United States",
        "Des Moines, Iowa, United States",
        "Wichita, Kansas, United States",
        "Topeka, Kansas, United States",
        "Frankfort, Kentucky, United States",
        "Lexington, Kentucky, United States",
        "Louisville, Kentucky, United States",
        "Baton Rouge, Louisiana, United States",
        "New Orleans, Louisiana, United States",
        "Augusta, Maine, United States",
        "Portland, Maine, United States",
        "Baltimore, Maryland, United States",
        "Annapolis, Maryland, United States",
        "Boston, Massachusetts, United States",
        "Detroit, Michigan, United States",
        "Lansing, Michigan, United States",
        "Minneapolis, Minnesota, United States",
        "Saint Paul, Minnesota, United States",
        "Jackson, Mississippi, United States",
        "Kansas City, Missouri, United States",
        "St. Louis, Missouri, United States",
        "Jefferson City, Missouri, United States",
        "Billings, Montana, United States",
        "Helena, Montana, United States",
        "Lincoln, Nebraska, United States",
        "Omaha, Nebraska, United States",
        "Carson City, Nevada, United States",
        "Henderson, Nevada, United States",
        "Las Vegas, Nevada, United States",
        "North Las Vegas, Nevada, United States",
        "Concord, New Hampshire, United States",
        "Manchester, New Hampshire, United States",
        "Jersey City, New Jersey, United States",
        "Newark, New Jersey, United States",
        "Trenton, New Jersey, United States",
        "Albuquerque, New Mexico, United States",
        "Santa Fe, New Mexico, United States",
        "Albany, New York, United States",
        "Charlotte, North Carolina, United States",
        "Durham, North Carolina, United States",
        "Greensboro, North Carolina, United States",
        "Raleigh, North Carolina, United States",
        "Bismarck, North Dakota, United States",
        "Fargo, North Dakota, United States",
        "Cincinnati, Ohio, United States",
        "Cleveland, Ohio, United States",
        "Columbus, Ohio, United States",
        "Oklahoma City, Oklahoma, United States",
        "Tulsa, Oklahoma, United States",
        "Portland, Oregon, United States",
        "Salem, Oregon, United States",
        "Harrisburg, Pennsylvania, United States",
        "Philadelphia, Pennsylvania, United States",
        "Pittsburgh, Pennsylvania, United States",
        "Providence, Rhode Island, United States",
        "Charleston, South Carolina, United States",
        "Columbia, South Carolina, United States",
        "Pierre, South Dakota, United States",
        "Sioux Falls, South Dakota, United States",
        "Memphis, Tennessee, United States",
        "Nashville, Tennessee, United States",
        "Arlington, Texas, United States",
        "Corpus Christi, Texas, United States",
        "El Paso, Texas, United States",
        "Fort Worth, Texas, United States",
        "Plano, Texas, United States",
        "San Antonio, Texas, United States",
        "Salt Lake City, Utah, United States",
        "Burlington, Vermont, United States",
        "Montpelier, Vermont, United States",
        "Richmond, Virginia, United States",
        "Virginia Beach, Virginia, United States",
        "Olympia, Washington, United States",
        "Seattle, Washington, United States",
        "Charleston, West Virginia, United States",
        "Madison, Wisconsin, United States",
        "Milwaukee, Wisconsin, United States",
        "Cheyenne, Wyoming, United States",
        "Grand Island, Nebraska, United States",
        "Biloxi, Mississippi, United States",
        "Cedar Rapids, Iowa, United States",
        "Worcester, Massachusetts, United States",
        "Morgantown, West Virginia, United States",
    ],
}
