"""
Dictionary of country_abbreviations
"""
country_abbreviations = {
    "Latin America": (
        "Argentina, "
        "Bolivia, "
        "Brazil, "
        "Chile, "
        "Colombia, "
        "Ecuador, "
        "Guyana, "
        "Paraguay, "
        "Peru, "
        "Suriname, "
        "Uruguay, "
        "Venezuela, "
        "Belize, "
        "Costa Rica, "
        "El Salvador, "
        "Guatemala, "
        "Honduras, "
        "Nicaragua, "
        "Panama, "
        "Cuba, "
        "Dominican Republic, "
        "Haiti, "
        "Puerto Rico"),
    "LATAM": (
        "Argentina, "
        "Bolivia, "
        "Brazil, "
        "Chile, "
        "Colombia, "
        "Ecuador, "
        "Guyana, "
        "Paraguay, "
        "Peru, "
        "Suriname, "
        "Uruguay, "
        "Venezuela, "
        "Belize, "
        "Costa Rica, "
        "El Salvador, "
        "Guatemala, "
        "Honduras, "
        "Nicaragua, "
        "Panama, "
        "Cuba, "
        "Dominican Republic, "
        "Haiti, "
        "Puerto Rico"),
    "APAC": (
        "Australia, "
        "Bangladesh, "
        "Bhutan, "
        "Brunei, "
        "Cambodia, "
        "China, "
        "East Timor (Timor-Leste), "
        "Fiji, "
        "India, "
        "Indonesia, "
        "Japan, "
        "Laos, "
        "Malaysia, "
        "Maldives, "
        "Mongolia, "
        "Myanmar (Burma), "
        "Nepal, "
        "New Zealand, "
        "Pakistan, "
        "Papua New Guinea, "
        "Philippines, "
        "Singapore, "
        "South Korea, "
        "Sri Lanka, "
        "Taiwan, "
        "Thailand, "
        "Vanuatu, "
        "Vietnam"),
    "EMEA": (
        "Albania, "
        "Algeria, "
        "Andorra, "
        "Angola, "
        "Armenia, "
        "Austria, "
        "Azerbaijan, "
        "Bahrain, "
        "Belarus, "
        "Belgium, "
        "Benin, "
        "Bosnia and Herzegovina, "
        "Botswana, "
        "Bulgaria, "
        "Burkina Faso, "
        "Burundi, "
        "Cape Verde, "
        "Central African Republic, "
        "Chad, "
        "Comoros, "
        "Croatia, "
        "Cyprus, "
        "Czech Republic, "
        "Denmark, "
        "Djibouti, "
        "Egypt, "
        "Equatorial Guinea, "
        "Estonia, "
        "Eswatini, "
        "Ethiopia, "
        "Finland, "
        "France, "
        "Gabon, "
        "Gambia, "
        "Georgia, "
        "Germany, "
        "Ghana, "
        "Greece, "
        "Guinea, "
        "Guinea-Bissau, "
        "Hungary, "
        "Iceland, "
        "Iraq, "
        "Ireland, "
        "Israel, "
        "Italy, "
        "Ivory Coast, "
        "Jordan, "
        "Kazakhstan, "
        "Kenya, "
        "Kuwait, "
        "Kyrgyzstan, "
        "Latvia, "
        "Lebanon, "
        "Lesotho, "
        "Liberia, "
        "Libya, "
        "Lithuania, "
        "Luxembourg, "
        "Malawi, "
        "Mali, "
        "Malta, "
        "Mauritania, "
        "Mauritius, "
        "Moldova, "
        "Monaco, "
        "Montenegro, "
        "Morocco, "
        "Mozambique, "
        "Namibia, "
        "Netherlands, "
        "Niger, "
        "Nigeria, "
        "North Macedonia, "
        "Norway, "
        "Oman, "
        "Palestine, "
        "Poland, "
        "Portugal, "
        "Qatar, "
        "Romania, "
        "Russia, "
        "Rwanda, "
        "San Marino, "
        "Sao Tome and Principe, "
        "Saudi Arabia, "
        "Senegal, "
        "Serbia, "
        "Seychelles, "
        "Sierra Leone, "
        "Slovakia, "
        "Slovenia, "
        "Somalia, "
        "South Africa, "
        "South Sudan, "
        "Spain, "
        "Sudan, "
        "Sweden, "
        "Switzerland, "
        "Syria, "
        "Tajikistan, "
        "Tanzania, "
        "Togo, "
        "Tunisia, "
        "Turkey, "
        "Turkmenistan, "
        "Uganda, "
        "Ukraine, "
        "United Arab Emirates, "
        "United Kingdom, "
        "Uzbekistan, "
        "Vatican City, "
        "Yemen, "
        "Zambia, "
        "Zimbabwe"
    ),
    "NA": (
        "Canada, "
        "Mexico, "
        "United States"
    ),
    "EU": (
        "Austria, "
        "Belgium, "
        "Bulgaria, "
        "Croatia, "
        "Cyprus, "
        "Czech Republic, "
        "Denmark, "
        "Estonia, "
        "Finland, "
        "France, "
        "Germany, "
        "Greece, "
        "Hungary, "
        "Ireland, "
        "Italy, "
        "Latvia, "
        "Lithuania, "
        "Luxembourg, "
        "Malta, "
        "Netherlands, "
        "Poland, "
        "Portugal, "
        "Romania, "
        "Slovakia, "
        "Slovenia, "
        "Spain, "
        "Sweden' "
    ),
    "MEA": (
        "Algeria, "
        "Angola, "
        "Bahrain, "
        "Botswana, "
        "Burundi, "
        "Comoros, "
        "Djibouti, "
        "Egypt, "
        "Eritrea, "
        "Eswatini, "
        "Ethiopia, "
        "Gabon, "
        "Gambia, "
        "Ghana, "
        "Guinea, "
        "Iran, "
        "Iraq, "
        "Israel, "
        "Jordan, "
        "Kenya, "
        "Kuwait, "
        "Lebanon, "
        "Lesotho, "
        "Liberia, "
        "Libya, "
        "Madagascar, "
        "Malawi, "
        "Mauritania, "
        "Mauritius, "
        "Morocco, "
        "Mozambique, "
        "Namibia, "
        "Niger, "
        "Nigeria, "
        "Oman, "
        "Palestine, "
        "Qatar, "
        "Rwanda, "
        "Saudi Arabia ",
        "Senegal, "
        "Seychelles, "
        "Sierra Leone ",
        "Somalia, "
        "South Africa ",
        "South Sudan ",
        "Sudan, "
        "Syria, "
        "Tanzania, "
        "Togo, "
        "Tunisia, "
        "Uganda, "
        "United Arab Emirates, "
        "Yemen, "
        "Zambia, "
        "Zimbabwe "
    ),
    "ANZ": (
        'Australia, ',
        'New Zealand'
    ),
    "BRICS": (
        "Brazil, "
        "Russia, "
        "India, "
        "China, "
        "South Africa"
    )
}
